# Generated by Django 3.1.7 on 2021-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stringsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
