# Generated by Django 3.1.7 on 2021-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stringsapp', '0002_inputstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenum',
            name='name',
        ),
        migrations.AlterField(
            model_name='inputstring',
            name='source',
            field=models.TextField(),
        ),
    ]
